### PR TITLE
Fix vpn connection.

### LINKED ISSUE #8: push "dhcp-option DNS X.X.X.X"
Библиотека openvpn в Амнезии не принимает опции push DNS server от сервера, а наши ключи не содержат явного указания на DNS. Мы можем добавить жестко их в файл, но это не очень хорошо в смысле гибкости.
Правильнее сделать так чтобы клиентская библиотека openvpn обрабатывала эти опции и использовала DNS которые выдает сервер

push "dhcp-option DNS X.X.X.X"

### PR DESCRIPTION
**Pull request by Vipon**
Fix PUSH, route and dhcp-option DNS.

issue: #8 #9

### CODE REVIEW

File: client/vpnconnection.h [hunk 1]
```diff
@@ -46,24 +46,33 @@ class VpnConnection : public QObject
...
+
 signals:
     void bytesChanged(quint64 receivedBytes, quint64 sentBytes);
     void connectionStateChanged(Vpn::ConnectionState state);
     void vpnProtocolError(amnezia::ErrorCode error);
 
     void serviceIsNotReady();
 
+    void newRoute(const QString& ip);
+    void newDns(const QString& dnsAddr);
```
Comment (Vipon) [inline client/vpnconnection.h]: Remove useless.

File: client/ui/models/servers_model.cpp [hunk 2]
```diff
@@ -504,6 +504,15 @@ bool ServersModel::isAmneziaDnsContainerInstalled(const int serverIndex) const
     return false;
 }
 
+void ServersModel::setNewDns(QString dnsAddr)
```
Comment (Vipon) [inline client/ui/models/servers_model.cpp]: Remove function, new dns is set up with other way.

File: client/ui/models/servers_model.h [hunk 3]
```diff
@@ -56,6 +56,8 @@ class ServersModel : public QAbstractListModel
     Q_PROPERTY(int processedIndex READ getProcessedServerIndex WRITE setProcessedServerIndex NOTIFY processedServerIndexChanged)
 
 public slots:
+    void setNewDns(QString dnsAddr);
```
Comment (Vipon) [inline client/ui/models/servers_model.h]: Remove definition

File: client/ui/models/sites_model.cpp [hunk 4]
```diff
@@ -42,6 +42,7 @@ QVariant SitesModel::data(const QModelIndex &index, int role) const
 
 bool SitesModel::addSite(const QString &hostname, const QString &ip)
 {
+    qDebug() << "site_model.cpp: addSite: routeMode: " << m_currentRouteMode << ", hostname: " << hostname << ", ip: " << ip << "\n";
```
Comment (Vipon) [inline client/ui/models/sites_model.cpp]: Remove debug comment
